os: linux
language: cpp
compiler: g++

jobs:
  include:
    - os: linux
      dist: focal
    - os: linux
      dist: bionic

branches:
  only:
    - devel
    - /^v\d+\.\d+\.\d+.*$/  # version tags

services:
  - docker
  
notifications:
  email:
    recipients:
      - francesco.ruscelli@iit.it
      - arturo.laurenzi@iit.it
      - enrico.mingo@pal-robotics.com
    on_success: never
    on_failure: always

before_install:
  - rm -rf /opt/pyenv

before_script:
  - echo "Travis tag is $TRAVIS_TAG"
  - sudo sh -c 'echo "deb http://packages.ros.org/ros/ubuntu $(lsb_release -sc) main" > /etc/apt/sources.list.d/ros-latest.list'
  - curl -s https://raw.githubusercontent.com/ros/rosdistro/master/ros.asc | sudo apt-key add -
  - sudo apt update && sudo apt install libgtest-dev libyaml-cpp-dev python3-pip python3-setuptools liburdfdom-dev cmake libeigen3-dev libboost-filesystem-dev libboost-serialization-dev libblas-dev liblapack-dev patchelf python3-venv
  - sudo pip3 install build twine hhcm_forest==0.0.26
  - SRC_DIR=$PWD
  - BUILD_DIR=$PWD/build
  - FOREST_DIR=$PWD/../forest_ws
  - mkdir $BUILD_DIR
  - mkdir $FOREST_DIR
  - cd $FOREST_DIR
  - forest --init
  - source setup.bash
  - ln -s $SRC_DIR src/$(basename $SRC_DIR)  # symlink original source folder
  - forest -a git@github.com:advrhumanoids/multidof_recipes.git master -u --clone-protocol https  # get recipes

script: 
  - FOREST_ARGS="--default-build-type Release --clone-protocol https --verbose -j2"
  - cd $FOREST_DIR
  - forest casadi $FOREST_ARGS
  - forest pybind11 $FOREST_ARGS
  - cd src/horizon
  - pip3 install .
  - python3 horizon/tests/test_get_set.py
  - if [ -z $TRAVIS_TAG ]; then 
       echo "Not a tag build, will not upload to pypi"; 
    else
       # upload to pypi
       python3 -m build --wheel
       twine upload -u __token__ -p $PYPI_TOKEN dist/*.whl
       # upload to docker
       REPO=francescoruscelli
       cd docker && ./build
       docker tag horizon $REPO/horizon
       docker login --username=$REPO --password=$DOCKER_TOKEN
       docker push $REPO/horizon;
    
    fi


