# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/widget1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1225, 912)
        Form.setMouseTracking(False)
        self.CT = QtWidgets.QGroupBox(Form)
        self.CT.setGeometry(QtCore.QRect(570, 20, 501, 131))
        self.CT.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.CT.setAlignment(QtCore.Qt.AlignCenter)
        self.CT.setObjectName("CT")
        self.gridLayoutWidget = QtWidgets.QWidget(self.CT)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 20, 321, 111))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.CTGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.CTGrid.setContentsMargins(0, 0, 0, 0)
        self.CTGrid.setSpacing(0)
        self.CTGrid.setObjectName("CTGrid")
        self.CTName = QtWidgets.QLabel(self.gridLayoutWidget)
        self.CTName.setObjectName("CTName")
        self.CTGrid.addWidget(self.CTName, 0, 0, 1, 1)
        self.CTNameInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.CTNameInput.setObjectName("CTNameInput")
        self.CTGrid.addWidget(self.CTNameInput, 0, 1, 1, 1)
        self.CTButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.CTButton.setObjectName("CTButton")
        self.CTGrid.addWidget(self.CTButton, 2, 0, 1, 3)
        self.CTFunction = QtWidgets.QLabel(self.gridLayoutWidget)
        self.CTFunction.setObjectName("CTFunction")
        self.CTGrid.addWidget(self.CTFunction, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.CTGrid.addItem(spacerItem, 0, 2, 1, 1)
        self.CTFunctionInput = LineEdit(self.gridLayoutWidget)
        self.CTFunctionInput.setObjectName("CTFunctionInput")
        self.CTGrid.addWidget(self.CTFunctionInput, 1, 1, 1, 2)
        self.CTList = QtWidgets.QListWidget(self.CT)
        self.CTList.setGeometry(QtCore.QRect(360, 30, 131, 91))
        self.CTList.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked|QtWidgets.QAbstractItemView.EditKeyPressed)
        self.CTList.setDragEnabled(True)
        self.CTList.setDragDropMode(QtWidgets.QAbstractItemView.DragOnly)
        self.CTList.setObjectName("CTList")
        self.SV = QtWidgets.QGroupBox(Form)
        self.SV.setGeometry(QtCore.QRect(10, 20, 531, 131))
        self.SV.setAlignment(QtCore.Qt.AlignCenter)
        self.SV.setFlat(False)
        self.SV.setCheckable(False)
        self.SV.setObjectName("SV")
        self.SVAddButton = QtWidgets.QPushButton(self.SV)
        self.SVAddButton.setGeometry(QtCore.QRect(110, 90, 131, 22))
        self.SVAddButton.setObjectName("SVAddButton")
        self.SVNameInput = QtWidgets.QLineEdit(self.SV)
        self.SVNameInput.setGeometry(QtCore.QRect(51, 37, 41, 20))
        self.SVNameInput.setObjectName("SVNameInput")
        self.SVName = QtWidgets.QLabel(self.SV)
        self.SVName.setGeometry(QtCore.QRect(8, 40, 59, 14))
        self.SVName.setObjectName("SVName")
        self.SVNodeInput = NodesSpinBox(self.SV)
        self.SVNodeInput.setGeometry(QtCore.QRect(239, 36, 91, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(87, 49, 198, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(87, 49, 198, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.SVNodeInput.setPalette(palette)
        self.SVNodeInput.setMaximum(102)
        self.SVNodeInput.setProperty("value", 0)
        self.SVNodeInput.setObjectName("SVNodeInput")
        self.SVNode = QtWidgets.QLabel(self.SV)
        self.SVNode.setGeometry(QtCore.QRect(198, 40, 40, 16))
        self.SVNode.setObjectName("SVNode")
        self.SVDim = QtWidgets.QLabel(self.SV)
        self.SVDim.setGeometry(QtCore.QRect(100, 40, 30, 16))
        self.SVDim.setObjectName("SVDim")
        self.SVDimInput = QtWidgets.QSpinBox(self.SV)
        self.SVDimInput.setGeometry(QtCore.QRect(141, 36, 47, 23))
        self.SVDimInput.setMinimum(1)
        self.SVDimInput.setObjectName("SVDimInput")
        self.line = QtWidgets.QFrame(self.SV)
        self.line.setGeometry(QtCore.QRect(110, 67, 118, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.SVTable = BoxStateVar(self.SV)
        self.SVTable.setGeometry(QtCore.QRect(350, 30, 161, 91))
        self.SVTable.setObjectName("SVTable")
        self.SVTable.setColumnCount(2)
        self.SVTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.SVTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SVTable.setHorizontalHeaderItem(1, item)
        self.SVTable.horizontalHeader().setDefaultSectionSize(57)
        self.SVTable.horizontalHeader().setMinimumSectionSize(20)
        self.SVTable.verticalHeader().setDefaultSectionSize(21)
        self.PRB = QtWidgets.QGroupBox(Form)
        self.PRB.setGeometry(QtCore.QRect(9, 160, 1061, 481))
        self.PRB.setObjectName("PRB")
        self.consoleLogger = ConsoleLogger(Form)
        self.consoleLogger.setGeometry(QtCore.QRect(10, 660, 1061, 192))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.consoleLogger.setFont(font)
        self.consoleLogger.setStyleSheet("QFrame {background-color: rgb(46, 52, 54)}\n"
"QTextEdit {color: rgb(238, 238, 236)}")
        self.consoleLogger.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.consoleLogger.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.consoleLogger.setReadOnly(True)
        self.consoleLogger.setObjectName("consoleLogger")
        self.actionExit = QtWidgets.QAction(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../../../../.designer/resources/rocket.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/../../../../.designer/resources/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.SVNameInput, self.SVDimInput)
        Form.setTabOrder(self.SVDimInput, self.SVNodeInput)
        Form.setTabOrder(self.SVNodeInput, self.SVAddButton)
        Form.setTabOrder(self.SVAddButton, self.CTNameInput)
        Form.setTabOrder(self.CTNameInput, self.CTFunctionInput)
        Form.setTabOrder(self.CTFunctionInput, self.CTButton)
        Form.setTabOrder(self.CTButton, self.CTList)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CT.setTitle(_translate("Form", "Constraints"))
        self.CTName.setText(_translate("Form", "name:"))
        self.CTButton.setText(_translate("Form", "Add Constraint"))
        self.CTFunction.setText(_translate("Form", "function:"))
        self.SV.setTitle(_translate("Form", "State Variables"))
        self.SVAddButton.setText(_translate("Form", "Add State Variable"))
        self.SVName.setText(_translate("Form", "Name:"))
        self.SVNode.setText(_translate("Form", "Node:"))
        self.SVDim.setText(_translate("Form", "Dim:"))
        item = self.SVTable.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Var"))
        item = self.SVTable.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Dim"))
        self.PRB.setTitle(_translate("Form", "Problem"))
        self.actionExit.setText(_translate("Form", "Exit"))
        self.actionExit.setToolTip(_translate("Form", "Exit Horizon GUI"))
        self.actionExit.setShortcut(_translate("Form", "Ctrl+E"))
        self.actionAbout.setText(_translate("Form", "About"))
        self.actionAbout.setToolTip(_translate("Form", "Info about Horizon GUI"))
        self.actionAbout.setShortcut(_translate("Form", "Ctrl+I"))
from custom_widgets.box_state_var import BoxStateVar
from custom_widgets.console_logger import ConsoleLogger
from custom_widgets.line_edit import LineEdit
from custom_widgets.nodes_spinbox import NodesSpinBox


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
