# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/widget1.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(816, 685)
        Form.setMouseTracking(False)
        self.CT = QtWidgets.QGroupBox(Form)
        self.CT.setGeometry(QtCore.QRect(500, 550, 301, 111))
        self.CT.setObjectName("CT")
        self.pushButton = QtWidgets.QPushButton(self.CT)
        self.pushButton.setGeometry(QtCore.QRect(80, 80, 111, 22))
        self.pushButton.setObjectName("pushButton")
        self.SV = QtWidgets.QGroupBox(Form)
        self.SV.setGeometry(QtCore.QRect(460, 20, 341, 131))
        self.SV.setAlignment(QtCore.Qt.AlignCenter)
        self.SV.setFlat(False)
        self.SV.setCheckable(False)
        self.SV.setObjectName("SV")
        self.SVAddButton = QtWidgets.QPushButton(self.SV)
        self.SVAddButton.setGeometry(QtCore.QRect(120, 100, 131, 22))
        self.SVAddButton.setObjectName("SVAddButton")
        self.SVNameInput = QtWidgets.QLineEdit(self.SV)
        self.SVNameInput.setGeometry(QtCore.QRect(51, 37, 41, 20))
        self.SVNameInput.setObjectName("SVNameInput")
        self.SVName = QtWidgets.QLabel(self.SV)
        self.SVName.setGeometry(QtCore.QRect(8, 40, 59, 14))
        self.SVName.setObjectName("SVName")
        self.SVNodeInput = NodesSpinBox(self.SV)
        self.SVNodeInput.setGeometry(QtCore.QRect(240, 36, 91, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(87, 49, 198, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(87, 49, 198, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.SVNodeInput.setPalette(palette)
        self.SVNodeInput.setMaximum(102)
        self.SVNodeInput.setProperty("value", 0)
        self.SVNodeInput.setObjectName("SVNodeInput")
        self.SVNode = QtWidgets.QLabel(self.SV)
        self.SVNode.setGeometry(QtCore.QRect(198, 40, 40, 16))
        self.SVNode.setObjectName("SVNode")
        self.SVDim = QtWidgets.QLabel(self.SV)
        self.SVDim.setGeometry(QtCore.QRect(100, 40, 30, 16))
        self.SVDim.setObjectName("SVDim")
        self.SVDimInput = QtWidgets.QSpinBox(self.SV)
        self.SVDimInput.setGeometry(QtCore.QRect(141, 36, 47, 23))
        self.SVDimInput.setMinimum(1)
        self.SVDimInput.setObjectName("SVDimInput")
        self.TableSV = QtWidgets.QTableWidget(Form)
        self.TableSV.setGeometry(QtCore.QRect(20, 541, 461, 121))
        self.TableSV.setObjectName("TableSV")
        self.TableSV.setColumnCount(3)
        self.TableSV.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TableSV.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableSV.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TableSV.setHorizontalHeaderItem(2, item)
        self.PRB = QtWidgets.QGroupBox(Form)
        self.PRB.setGeometry(QtCore.QRect(10, 340, 781, 171))
        self.PRB.setObjectName("PRB")
        self.verticalLayoutWidget = QtWidgets.QWidget(Form)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(120, 90, 160, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.penis = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.penis.setObjectName("penis")
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(600, 220, 120, 80))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.actionExit = QtWidgets.QAction(Form)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../../../../../.designer/resources/rocket.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(Form)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../../../../../.designer/resources/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.CT.setTitle(_translate("Form", "Constraints"))
        self.pushButton.setText(_translate("Form", "Add Constraint"))
        self.SV.setTitle(_translate("Form", "State Variables"))
        self.SVAddButton.setText(_translate("Form", "Add State Variable"))
        self.SVName.setText(_translate("Form", "Name:"))
        self.SVNode.setText(_translate("Form", "Node:"))
        self.SVDim.setText(_translate("Form", "Dim:"))
        item = self.TableSV.horizontalHeaderItem(0)
        item.setText(_translate("Form", "State Variable"))
        item = self.TableSV.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Dimension"))
        item = self.TableSV.horizontalHeaderItem(2)
        item.setText(_translate("Form", "Usage"))
        self.PRB.setTitle(_translate("Form", "Problem"))
        self.actionExit.setText(_translate("Form", "Exit"))
        self.actionExit.setToolTip(_translate("Form", "Exit Horizon GUI"))
        self.actionExit.setShortcut(_translate("Form", "Ctrl+E"))
        self.actionAbout.setText(_translate("Form", "About"))
        self.actionAbout.setToolTip(_translate("Form", "Info about Horizon GUI"))
        self.actionAbout.setShortcut(_translate("Form", "Ctrl+I"))

from custom_widgets.nodes_spinbox import NodesSpinBox
