# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/untitled.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1288, 618)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(Form)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.SVNameInput_2 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SVNameInput_2.sizePolicy().hasHeightForWidth())
        self.SVNameInput_2.setSizePolicy(sizePolicy)
        self.SVNameInput_2.setObjectName("SVNameInput_2")
        self.gridLayout.addWidget(self.SVNameInput_2, 0, 1, 1, 1)
        self.SVDimInput_2 = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SVDimInput_2.sizePolicy().hasHeightForWidth())
        self.SVDimInput_2.setSizePolicy(sizePolicy)
        self.SVDimInput_2.setMinimum(1)
        self.SVDimInput_2.setObjectName("SVDimInput_2")
        self.gridLayout.addWidget(self.SVDimInput_2, 1, 1, 1, 1)
        self.SVNode_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SVNode_2.sizePolicy().hasHeightForWidth())
        self.SVNode_2.setSizePolicy(sizePolicy)
        self.SVNode_2.setObjectName("SVNode_2")
        self.gridLayout.addWidget(self.SVNode_2, 1, 2, 1, 1)
        self.SVName_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SVName_2.sizePolicy().hasHeightForWidth())
        self.SVName_2.setSizePolicy(sizePolicy)
        self.SVName_2.setObjectName("SVName_2")
        self.gridLayout.addWidget(self.SVName_2, 0, 0, 1, 1)
        self.SVAddButton_2 = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SVAddButton_2.sizePolicy().hasHeightForWidth())
        self.SVAddButton_2.setSizePolicy(sizePolicy)
        self.SVAddButton_2.setObjectName("SVAddButton_2")
        self.gridLayout.addWidget(self.SVAddButton_2, 2, 1, 1, 1)
        self.SVDim_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SVDim_2.sizePolicy().hasHeightForWidth())
        self.SVDim_2.setSizePolicy(sizePolicy)
        self.SVDim_2.setObjectName("SVDim_2")
        self.gridLayout.addWidget(self.SVDim_2, 1, 0, 1, 1)
        self.SVNodeInput_2 = NodesSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SVNodeInput_2.sizePolicy().hasHeightForWidth())
        self.SVNodeInput_2.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(87, 49, 198, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(87, 49, 198, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.SVNodeInput_2.setPalette(palette)
        self.SVNodeInput_2.setMaximum(102)
        self.SVNodeInput_2.setProperty("value", 0)
        self.SVNodeInput_2.setObjectName("SVNodeInput_2")
        self.gridLayout.addWidget(self.SVNodeInput_2, 1, 3, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 1, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 3, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.SVTable_2 = BoxStateVar(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.SVTable_2.sizePolicy().hasHeightForWidth())
        self.SVTable_2.setSizePolicy(sizePolicy)
        self.SVTable_2.setObjectName("SVTable_2")
        self.SVTable_2.setColumnCount(2)
        self.SVTable_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.SVTable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SVTable_2.setHorizontalHeaderItem(1, item)
        self.SVTable_2.horizontalHeader().setDefaultSectionSize(57)
        self.SVTable_2.horizontalHeader().setMinimumSectionSize(20)
        self.SVTable_2.horizontalHeader().setSortIndicatorShown(False)
        self.SVTable_2.verticalHeader().setDefaultSectionSize(21)
        self.horizontalLayout_2.addWidget(self.SVTable_2)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.funNameInput_2 = QtWidgets.QLineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.funNameInput_2.sizePolicy().hasHeightForWidth())
        self.funNameInput_2.setSizePolicy(sizePolicy)
        self.funNameInput_2.setObjectName("funNameInput_2")
        self.gridLayout_2.addWidget(self.funNameInput_2, 0, 1, 1, 1)
        self.funInput_2 = LineEdit(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.funInput_2.sizePolicy().hasHeightForWidth())
        self.funInput_2.setSizePolicy(sizePolicy)
        self.funInput_2.setObjectName("funInput_2")
        self.gridLayout_2.addWidget(self.funInput_2, 1, 1, 1, 1)
        self.funButton_2 = QtWidgets.QPushButton(self.widget)
        self.funButton_2.setObjectName("funButton_2")
        self.gridLayout_2.addWidget(self.funButton_2, 2, 1, 1, 1)
        self.funNameLabel_2 = QtWidgets.QLabel(self.widget)
        self.funNameLabel_2.setObjectName("funNameLabel_2")
        self.gridLayout_2.addWidget(self.funNameLabel_2, 0, 0, 1, 1)
        self.funLabel_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.funLabel_2.sizePolicy().hasHeightForWidth())
        self.funLabel_2.setSizePolicy(sizePolicy)
        self.funLabel_2.setObjectName("funLabel_2")
        self.gridLayout_2.addWidget(self.funLabel_2, 1, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 3, 1, 1, 1)
        self.funTable_2 = BoxFunction(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.funTable_2.sizePolicy().hasHeightForWidth())
        self.funTable_2.setSizePolicy(sizePolicy)
        self.funTable_2.setObjectName("funTable_2")
        self.funTable_2.setColumnCount(2)
        self.funTable_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.funTable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.funTable_2.setHorizontalHeaderItem(1, item)
        self.gridLayout_2.addWidget(self.funTable_2, 0, 2, 4, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem3, 3, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.NodesLabel_2 = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NodesLabel_2.sizePolicy().hasHeightForWidth())
        self.NodesLabel_2.setSizePolicy(sizePolicy)
        self.NodesLabel_2.setMinimumSize(QtCore.QSize(138, 17))
        self.NodesLabel_2.setObjectName("NodesLabel_2")
        self.verticalLayout.addWidget(self.NodesLabel_2)
        self.NodesSpinBox_2 = QtWidgets.QSpinBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.NodesSpinBox_2.sizePolicy().hasHeightForWidth())
        self.NodesSpinBox_2.setSizePolicy(sizePolicy)
        self.NodesSpinBox_2.setMinimumSize(QtCore.QSize(0, 26))
        self.NodesSpinBox_2.setObjectName("NodesSpinBox_2")
        self.verticalLayout.addWidget(self.NodesSpinBox_2, 0, QtCore.Qt.AlignHCenter)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.switchPageButton_2 = QtWidgets.QPushButton(self.widget1)
        self.switchPageButton_2.setObjectName("switchPageButton_2")
        self.gridLayout_4.addWidget(self.switchPageButton_2, 1, 0, 1, 1)
        self.ProblemMain_2 = QtWidgets.QStackedWidget(self.widget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(3)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.ProblemMain_2.sizePolicy().hasHeightForWidth())
        self.ProblemMain_2.setSizePolicy(sizePolicy)
        self.ProblemMain_2.setObjectName("ProblemMain_2")
        self.CTPage_2 = QtWidgets.QWidget()
        self.CTPage_2.setObjectName("CTPage_2")
        self.ProblemMain_2.addWidget(self.CTPage_2)
        self.CFPage_2 = QtWidgets.QWidget()
        self.CFPage_2.setObjectName("CFPage_2")
        self.ProblemMain_2.addWidget(self.CFPage_2)
        self.gridLayout_4.addWidget(self.ProblemMain_2, 0, 0, 1, 2)
        self.LineView_2 = QtWidgets.QHBoxLayout()
        self.LineView_2.setObjectName("LineView_2")
        self.label_2 = QtWidgets.QLabel(self.widget1)
        self.label_2.setObjectName("label_2")
        self.LineView_2.addWidget(self.label_2)
        self.MultipleLineButton_2 = QtWidgets.QRadioButton(self.widget1)
        self.MultipleLineButton_2.setChecked(True)
        self.MultipleLineButton_2.setObjectName("MultipleLineButton_2")
        self.LineView_2.addWidget(self.MultipleLineButton_2)
        self.SingleLineButton_2 = QtWidgets.QRadioButton(self.widget1)
        self.SingleLineButton_2.setChecked(False)
        self.SingleLineButton_2.setObjectName("SingleLineButton_2")
        self.LineView_2.addWidget(self.SingleLineButton_2)
        self.gridLayout_4.addLayout(self.LineView_2, 1, 1, 1, 1)
        self.consoleLogger_2 = ConsoleLogger(self.splitter)
        self.consoleLogger_2.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.consoleLogger_2.sizePolicy().hasHeightForWidth())
        self.consoleLogger_2.setSizePolicy(sizePolicy)
        self.consoleLogger_2.setMaximumSize(QtCore.QSize(16777215, 200))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.consoleLogger_2.setFont(font)
        self.consoleLogger_2.setStyleSheet("QFrame {background-color: rgb(46, 52, 54)}\n"
"QTextEdit {color: rgb(238, 238, 236)}")
        self.consoleLogger_2.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.consoleLogger_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.consoleLogger_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.consoleLogger_2.setReadOnly(True)
        self.consoleLogger_2.setObjectName("consoleLogger_2")
        self.verticalLayout_2.addWidget(self.splitter)
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_2.addWidget(self.label_3)

        self.retranslateUi(Form)
        self.ProblemMain_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.SVNode_2.setText(_translate("Form", "Node:"))
        self.SVName_2.setText(_translate("Form", "Name:"))
        self.SVAddButton_2.setText(_translate("Form", "Add"))
        self.SVDim_2.setText(_translate("Form", "Dim:"))
        item = self.SVTable_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Var"))
        item = self.SVTable_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Dim"))
        self.funButton_2.setText(_translate("Form", "Add "))
        self.funNameLabel_2.setText(_translate("Form", "name:"))
        self.funLabel_2.setText(_translate("Form", "function:"))
        item = self.funTable_2.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Name"))
        item = self.funTable_2.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Function"))
        self.NodesLabel_2.setText(_translate("Form", "N. of Horizon nodes:"))
        self.switchPageButton_2.setText(_translate("Form", "Switch to Cost Functions "))
        self.label_2.setText(_translate("Form", "View:"))
        self.MultipleLineButton_2.setText(_translate("Form", "Multiple"))
        self.SingleLineButton_2.setText(_translate("Form", "Single"))
        self.label_3.setText(_translate("Form", "State Variables"))
from horizon_gui.custom_widgets.box_function import BoxFunction
from horizon_gui.custom_widgets.box_state_var import BoxStateVar
from horizon_gui.custom_widgets.console_logger import ConsoleLogger
from horizon_gui.custom_widgets.line_edit import LineEdit
from horizon_gui.custom_widgets.nodes_spinbox import NodesSpinBox
