# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/widget1.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HorizonGUI(object):
    def setupUi(self, HorizonGUI):
        HorizonGUI.setObjectName("HorizonGUI")
        HorizonGUI.resize(1225, 912)
        HorizonGUI.setMouseTracking(False)
        self.funBox = QtWidgets.QGroupBox(HorizonGUI)
        self.funBox.setGeometry(QtCore.QRect(570, 10, 641, 201))
        self.funBox.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.funBox.setAlignment(QtCore.Qt.AlignCenter)
        self.funBox.setObjectName("funBox")
        self.gridLayoutWidget = QtWidgets.QWidget(self.funBox)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 30, 291, 161))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.CTGrid = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.CTGrid.setContentsMargins(0, 0, 0, 0)
        self.CTGrid.setSpacing(0)
        self.CTGrid.setObjectName("CTGrid")
        self.funNameLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.funNameLabel.setObjectName("funNameLabel")
        self.CTGrid.addWidget(self.funNameLabel, 0, 0, 1, 1)
        self.funNameInput = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.funNameInput.setObjectName("funNameInput")
        self.CTGrid.addWidget(self.funNameInput, 0, 1, 1, 1)
        self.funButton = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.funButton.setObjectName("funButton")
        self.CTGrid.addWidget(self.funButton, 2, 0, 1, 3)
        self.funLabel = QtWidgets.QLabel(self.gridLayoutWidget)
        self.funLabel.setObjectName("funLabel")
        self.CTGrid.addWidget(self.funLabel, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.CTGrid.addItem(spacerItem, 0, 2, 1, 1)
        self.funInput = LineEdit(self.gridLayoutWidget)
        self.funInput.setObjectName("funInput")
        self.CTGrid.addWidget(self.funInput, 1, 1, 1, 2)
        self.funTable = BoxFunction(self.funBox)
        self.funTable.setGeometry(QtCore.QRect(320, 30, 311, 161))
        self.funTable.setObjectName("funTable")
        self.funTable.setColumnCount(2)
        self.funTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.funTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.funTable.setHorizontalHeaderItem(1, item)
        self.SV = QtWidgets.QGroupBox(HorizonGUI)
        self.SV.setGeometry(QtCore.QRect(10, 10, 381, 201))
        self.SV.setAlignment(QtCore.Qt.AlignCenter)
        self.SV.setFlat(False)
        self.SV.setCheckable(False)
        self.SV.setObjectName("SV")
        self.SVAddButton = QtWidgets.QPushButton(self.SV)
        self.SVAddButton.setGeometry(QtCore.QRect(30, 130, 131, 22))
        self.SVAddButton.setObjectName("SVAddButton")
        self.SVNameInput = QtWidgets.QLineEdit(self.SV)
        self.SVNameInput.setGeometry(QtCore.QRect(51, 50, 41, 20))
        self.SVNameInput.setObjectName("SVNameInput")
        self.SVName = QtWidgets.QLabel(self.SV)
        self.SVName.setGeometry(QtCore.QRect(8, 52, 41, 16))
        self.SVName.setObjectName("SVName")
        self.SVNodeInput = NodesSpinBox(self.SV)
        self.SVNodeInput.setGeometry(QtCore.QRect(70, 80, 81, 23))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(87, 49, 198, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(87, 49, 198, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.HighlightedText, brush)
        brush = QtGui.QBrush(QtGui.QColor(145, 141, 126))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Highlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.HighlightedText, brush)
        self.SVNodeInput.setPalette(palette)
        self.SVNodeInput.setMaximum(102)
        self.SVNodeInput.setProperty("value", 0)
        self.SVNodeInput.setObjectName("SVNodeInput")
        self.SVNode = QtWidgets.QLabel(self.SV)
        self.SVNode.setGeometry(QtCore.QRect(32, 82, 40, 16))
        self.SVNode.setObjectName("SVNode")
        self.SVDim = QtWidgets.QLabel(self.SV)
        self.SVDim.setGeometry(QtCore.QRect(100, 50, 30, 16))
        self.SVDim.setObjectName("SVDim")
        self.SVDimInput = QtWidgets.QSpinBox(self.SV)
        self.SVDimInput.setGeometry(QtCore.QRect(130, 50, 41, 20))
        self.SVDimInput.setMinimum(1)
        self.SVDimInput.setObjectName("SVDimInput")
        self.line = QtWidgets.QFrame(self.SV)
        self.line.setGeometry(QtCore.QRect(17, 110, 151, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.SVTable = BoxStateVar(self.SV)
        self.SVTable.setGeometry(QtCore.QRect(190, 30, 181, 161))
        self.SVTable.setObjectName("SVTable")
        self.SVTable.setColumnCount(2)
        self.SVTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.SVTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.SVTable.setHorizontalHeaderItem(1, item)
        self.SVTable.horizontalHeader().setDefaultSectionSize(57)
        self.SVTable.horizontalHeader().setMinimumSectionSize(20)
        self.SVTable.horizontalHeader().setSortIndicatorShown(False)
        self.SVTable.verticalHeader().setDefaultSectionSize(21)
        self.PRB = QtWidgets.QGroupBox(HorizonGUI)
        self.PRB.setGeometry(QtCore.QRect(9, 220, 1201, 451))
        self.PRB.setObjectName("PRB")
        self.formLayoutWidget = QtWidgets.QWidget(self.PRB)
        self.formLayoutWidget.setGeometry(QtCore.QRect(850, 410, 201, 31))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.LineView = QtWidgets.QHBoxLayout(self.formLayoutWidget)
        self.LineView.setContentsMargins(0, 0, 0, 0)
        self.LineView.setObjectName("LineView")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        self.label.setObjectName("label")
        self.LineView.addWidget(self.label)
        self.MultipleLine = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.MultipleLine.setObjectName("MultipleLine")
        self.LineView.addWidget(self.MultipleLine)
        self.SingleLine = QtWidgets.QRadioButton(self.formLayoutWidget)
        self.SingleLine.setChecked(True)
        self.SingleLine.setObjectName("SingleLine")
        self.LineView.addWidget(self.SingleLine)
        self.ProblemMain = QtWidgets.QStackedWidget(self.PRB)
        self.ProblemMain.setGeometry(QtCore.QRect(2, 20, 1191, 381))
        self.ProblemMain.setObjectName("ProblemMain")
        self.CTPage = QtWidgets.QWidget()
        self.CTPage.setObjectName("CTPage")
        self.label_2 = QtWidgets.QLabel(self.CTPage)
        self.label_2.setGeometry(QtCore.QRect(490, 10, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.ProblemMain.addWidget(self.CTPage)
        self.CFPage = QtWidgets.QWidget()
        self.CFPage.setObjectName("CFPage")
        self.label_3 = QtWidgets.QLabel(self.CFPage)
        self.label_3.setGeometry(QtCore.QRect(470, 10, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.ProblemMain.addWidget(self.CFPage)
        self.switchPageButton = QtWidgets.QPushButton(self.PRB)
        self.switchPageButton.setGeometry(QtCore.QRect(440, 410, 191, 25))
        self.switchPageButton.setObjectName("switchPageButton")
        self.consoleLogger = ConsoleLogger(HorizonGUI)
        self.consoleLogger.setGeometry(QtCore.QRect(10, 680, 1201, 192))
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.consoleLogger.setFont(font)
        self.consoleLogger.setStyleSheet("QFrame {background-color: rgb(46, 52, 54)}\n"
"QTextEdit {color: rgb(238, 238, 236)}")
        self.consoleLogger.setFrameShape(QtWidgets.QFrame.WinPanel)
        self.consoleLogger.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.consoleLogger.setReadOnly(True)
        self.consoleLogger.setObjectName("consoleLogger")
        self.actionExit = QtWidgets.QAction(HorizonGUI)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/../../../../../../../.designer/resources/rocket.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionExit.setIcon(icon)
        self.actionExit.setObjectName("actionExit")
        self.actionAbout = QtWidgets.QAction(HorizonGUI)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("ui/../../../../../../../.designer/resources/info.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionAbout.setIcon(icon1)
        self.actionAbout.setObjectName("actionAbout")

        self.retranslateUi(HorizonGUI)
        self.ProblemMain.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(HorizonGUI)
        HorizonGUI.setTabOrder(self.SVNameInput, self.SVDimInput)
        HorizonGUI.setTabOrder(self.SVDimInput, self.SVNodeInput)
        HorizonGUI.setTabOrder(self.SVNodeInput, self.SVAddButton)
        HorizonGUI.setTabOrder(self.SVAddButton, self.funNameInput)
        HorizonGUI.setTabOrder(self.funNameInput, self.funInput)
        HorizonGUI.setTabOrder(self.funInput, self.funButton)

    def retranslateUi(self, HorizonGUI):
        _translate = QtCore.QCoreApplication.translate
        HorizonGUI.setWindowTitle(_translate("HorizonGUI", "Form"))
        self.funBox.setTitle(_translate("HorizonGUI", "Functions"))
        self.funNameLabel.setText(_translate("HorizonGUI", "name:"))
        self.funButton.setText(_translate("HorizonGUI", "Add Constraint"))
        self.funLabel.setText(_translate("HorizonGUI", "function:"))
        item = self.funTable.horizontalHeaderItem(0)
        item.setText(_translate("HorizonGUI", "Name"))
        item = self.funTable.horizontalHeaderItem(1)
        item.setText(_translate("HorizonGUI", "Function"))
        self.SV.setTitle(_translate("HorizonGUI", "State Variables"))
        self.SVAddButton.setText(_translate("HorizonGUI", "Add State Variable"))
        self.SVName.setText(_translate("HorizonGUI", "Name:"))
        self.SVNode.setText(_translate("HorizonGUI", "Node:"))
        self.SVDim.setText(_translate("HorizonGUI", "Dim:"))
        item = self.SVTable.horizontalHeaderItem(0)
        item.setText(_translate("HorizonGUI", "Var"))
        item = self.SVTable.horizontalHeaderItem(1)
        item.setText(_translate("HorizonGUI", "Dim"))
        self.PRB.setTitle(_translate("HorizonGUI", "Problem"))
        self.label.setText(_translate("HorizonGUI", "View:"))
        self.MultipleLine.setText(_translate("HorizonGUI", "Multiple"))
        self.SingleLine.setText(_translate("HorizonGUI", "Single"))
        self.label_2.setText(_translate("HorizonGUI", "Constraints"))
        self.label_3.setText(_translate("HorizonGUI", "Cost Functions"))
        self.switchPageButton.setText(_translate("HorizonGUI", "Switch to Cost Functions "))
        self.actionExit.setText(_translate("HorizonGUI", "Exit"))
        self.actionExit.setToolTip(_translate("HorizonGUI", "Exit Horizon GUI"))
        self.actionExit.setShortcut(_translate("HorizonGUI", "Ctrl+E"))
        self.actionAbout.setText(_translate("HorizonGUI", "About"))
        self.actionAbout.setToolTip(_translate("HorizonGUI", "Info about Horizon GUI"))
        self.actionAbout.setShortcut(_translate("HorizonGUI", "Ctrl+I"))
from horizon_gui.custom_widgets.box_function import BoxFunction
from horizon_gui.custom_widgets.box_state_var import BoxStateVar
from horizon_gui.custom_widgets.console_logger import ConsoleLogger
from horizon_gui.custom_widgets.line_edit import LineEdit
from horizon_gui.custom_widgets.nodes_spinbox import NodesSpinBox
